.Dd Apr 16, 2023
.Dt CC 0.1.3
.Os MP MicroKernel

.Sh NAME
.Nm cc
.Nd C/C++ Compiler for MP MicroKernel

.Sh Synopsis
.Nm cc <CompilerFlags> <InputFiles> -o <OutputFile>
or
.Nm c++ <CompilerFlags> <InputFiles> -o <OutputFile>
.Sh DESCRIPTION

The
.Nm cc
program compiles every C/C++ source code into a MP MicroKernel object.
