#
#	========================================================
#
#	MP MicroKernel
# 	Last rev: 14/11/2023
# 	Copyright Amlal EL Mahrouss, all rights reserved.
#
# 	========================================================
#

CC			= mcc

# in all because there's nothing else to do.
.PHONY: srv-fs
srv-fs:
	$(CC) --kernel --shared src/fs.c
